name: Deploy to dockerhub

on:
  push:
    branches: [ master ]
    
env:
  username: ${{ secrets.AWS_ACCESS_KEY_ID }}
  password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  repo: ${{ secrets.REPONAME }}
  
    
jobs:
  
  create-and-push-to-docker-hub:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    #- name: dockerlogin
    #  run: |
    #    docker login -u $username -p $password
    - name: todays date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      
    - name: building docker image
      run: docker build . --file Dockerfile --tag $username/python-api:${{ steps.date.outputs.date }}
    - name: pushing the image
      run: |
        docker login -u ${{ secrets.AWS_ACCESS_KEY_ID }} -p ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        docker push $username/python-api:${{ steps.date.outputs.date }}
  
    
  
